# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Crypto Exchange Python Programming Blog
email: hello@cuongitl.net
author: Sam McHardy
author-img: profile-img.jpeg # add your photo
description: >- # this means to ignore newlines until "baseurl:"
  Examples to use python with Binance, Kucoin and IDEX crytocurrency exchanges.
  Async programming, spot, futures and margin trading.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cuongitl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
twitter_username: cuongitl
twitter:
  username: cuongitl
github_username:  cuongitl
telegram_username:  cuongitl
reddit_username:  cuongitl

site-twitter: #if your site has a twitter account, enter it here

about-author: I am a developer focusing on python development. Author of many crypto exchange libraries. Always hungry to keep learning. # add description
social-twitter: cuongitl
social-facebook: # add your Facebook handle
social-github: cuongitl # add your Github handle
social-linkedin: cuongitl
social-email: cuongitl.b@gmail.com

analytics: UA-112162600-1 # Google Analytics
google_analytics: UA-112162600-1

social:
  name: Cuongitl
  links:
    - https://twitter.com/cuongitl
    - https://github.com/cuongitl
    - https://t.me/cuongitl

header_pages:
 - https://github.com/cuongitl/python-bitget
 - https://github.com/cuongitl/pyftx


binance_url: https://partner.bitget.com/bg/5TN49R
kucoin_url: https://signal.lecuong.info/s/bnb

python_binance_url: https://github.com/cuongitl/python-bitget
python_kucoin_url: https://github.com/cuongitl/pyftx

USDT(TRC20):  TSLE4b1VhkNZQ6YLnusq2XJzTykzeeUupD
# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-redirect-from

minima:
  date_format: "%b %-d, %Y"

disqus:
    shortname: cuongitl

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
